import {useEffect,useState} from 'react';
import {api} from './api';
import {PasswordInput} from './password-input';
type Admin={id:string;email:string;name:string;disabled:boolean;created_at:number;permissions:string[]};
const labels:Record<string,string>={stores:'Stores & settings',vendor_access:'Vendor accounts',subscriptions:'Subscription approvals',pricing:'Pricing settings',inventory:'Inventory',sales:'Sales',purchases:'Purchases & suppliers',reports:'Reports & expenses',wholesale:'Wholesale'};
export function AdminManagement(){const [admins,setAdmins]=useState<Admin[]>([]),[available,setAvailable]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[reset,setReset]=useState('');
 async function refresh(){try{const d=await api('/api/admins');setAdmins(d.admins);setAvailable(d.permissions)}catch(e){setMessage((e as Error).message)}}useEffect(()=>{void refresh()},[]);
 async function update(admin:Admin,action:string){setBusy(true);setReset('');try{const result=await api('/api/admins/'+admin.id,{action});if(result.code)setReset(location.origin+'/admin/login#reset='+encodeURIComponent(result.code));setMessage(action==='reset'?'Reset link created. Share it privately; it expires in one hour.':'Administrator access updated.');await refresh()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <div className="admin-layout global-admin-management"><section className="panel padded"><h2>Add administrator</h2><p className="muted">Choose only the sections this administrator needs.</p><form className="form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setBusy(true);setMessage('');try{await api('/api/admins',{name:f.get('name'),email:f.get('email'),password:f.get('password'),permissions:f.getAll('permissions')});form.reset();setMessage('Administrator created. Share the login details privately.');await refresh()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}><label>Name<input name="name" maxLength={100} required autoComplete="off"/></label><label>Email<input name="email" type="email" required autoComplete="off"/></label><label>Initial password<PasswordInput name="password" minLength={12} maxLength={128} required autoComplete="new-password"/></label><fieldset className="permission-grid"><legend>Allowed sections</legend>{available.map(p=><label key={p}><input name="permissions" type="checkbox" value={p}/>{labels[p]||p}</label>)}</fieldset><small className="muted">Use 12–128 characters. Permissions are enforced by the server.</small><button className="btn primary" disabled={busy}>Create administrator</button></form></section><section className="panel padded"><h2>Administrator accounts</h2><p role="status" className="status-message">{message}</p>{reset&&<div className="notice"><b>Private reset link</b><code className="break-anywhere">{reset}</code></div>}<div className="table-scroll admin-accounts-scroll"><table className="ledger-table admin-accounts-table"><thead><tr><th>Name / email</th><th>Access</th><th>Status</th><th>Actions</th></tr></thead><tbody>{admins.map(a=><AdminRow key={a.id} admin={a} available={available} busy={busy} update={async(action,permissions,profile)=>{setBusy(true);try{if(action==='permissions'||action==='profile'){await api('/api/admins/'+a.id,{action,...(action==='permissions'?{permissions}:profile)});setMessage(action==='profile'?'Administrator details updated. They must sign in again.':'Permissions saved. The administrator must sign in again.');await refresh()}else if(action==='delete'){await api('/api/admins/'+a.id,{action});setMessage('Administrator account deleted and signed out.');await refresh()}else await update(a,action)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}/>)}</tbody></table>{!admins.length&&<p className="empty-inline">No additional admins yet.</p>}</div></section></div>;
}
function AdminRow({admin:a,available,busy,update}:{admin:Admin;available:string[];busy:boolean;update:(action:string,permissions?:string[],profile?:{name:string;email:string})=>Promise<void>}){
 const [selected,setSelected]=useState(a.permissions),[editing,setEditing]=useState(false),[displayName,setDisplayName]=useState(a.name),[mail,setMail]=useState(a.email);
 useEffect(()=>{setSelected(a.permissions);setDisplayName(a.name);setMail(a.email)},[a.permissions,a.name,a.email]);
 return <tr><td><b>{a.name}</b><small className="block-text">{a.email}</small>{editing&&<form className="form admin-edit-form" onSubmit={e=>{e.preventDefault();void update('profile',undefined,{name:displayName,email:mail}).then(()=>setEditing(false))}}><label>Name<input value={displayName} maxLength={100} required onChange={e=>setDisplayName(e.target.value)}/></label><label>Email<input value={mail} type="email" required onChange={e=>setMail(e.target.value)}/></label><div className="actions"><button className="btn primary" disabled={busy}>Save details</button><button className="btn" type="button" onClick={()=>setEditing(false)}>Cancel</button></div></form>}</td><td><div className="permission-grid compact">{available.map(p=><label key={p}><input type="checkbox" checked={selected.includes(p)} onChange={e=>setSelected(e.target.checked?[...selected,p]:selected.filter(x=>x!==p))}/>{labels[p]||p}</label>)}</div><button className="text-button" disabled={busy||!selected.length} onClick={()=>void update('permissions',selected)}>Save access</button></td><td><span className={'badge '+(a.disabled?'amber':'green')}>{a.disabled?'Disabled':'Active'}</span></td><td><div className="actions"><button className="btn" disabled={busy} onClick={()=>setEditing(!editing)}>Edit</button><button className="btn" disabled={busy} onClick={()=>{if(confirm((a.disabled?'Enable ':'Disable ')+a.email+'?'))void update(a.disabled?'enable':'disable')}}>{a.disabled?'Enable':'Disable'}</button><button className="text-button danger" disabled={busy} onClick={()=>{if(confirm('Delete administrator '+a.email+'? Their account will be signed out and removed from the admin list.'))void update('delete')}}>Delete</button></div></td></tr>;
}
