import {useEffect,useState} from "react";
import {LogOut,RefreshCw,Search} from "lucide-react";
import {api,logout} from "./api";
import {money} from "@/lib/store";
import {businessTypes} from "@/lib/vendors";
import {PasswordInput} from "./password-input";
import {ThemeToggle} from "./theme";
import {AdminManagement} from "./admin-management";
import {SubscriptionApprovals} from "./subscription-approvals";
import {MarketplaceAdmin} from "./marketplace-admin";
import {WholesalePricingAdmin,WholesaleValidityAdmin} from "./wholesale-portal";
import {AccountPassword} from "./account-password";
import {PricingEditor} from "./pricing";

const stamp=(n:any)=>n?new Date(Number(n)).toLocaleDateString("en-IN"):"—";
export function AdminConsole({role,permissions}:{role:string;permissions:string[]}){
  const [tab,setTab]=useState("Vendors"),[rows,setRows]=useState<any>({vendors:[],wholesalers:[]}),[selected,setSelected]=useState<any>(),[search,setSearch]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[vendorPricing,setVendorPricing]=useState<any>();
  const allowed=(permission:string)=>role==="owner"||permissions.includes(permission);
  async function load(){try{setRows(await api("/api/admin/businesses"))}catch(error){setMessage((error as Error).message)}}
  useEffect(()=>{void load()},[]);
  async function open(type:string,id:string){try{setSelected(await api(`/api/admin/businesses/${type}/${encodeURIComponent(id)}`))}catch(error){setMessage((error as Error).message)}}
  const tabs=[...(allowed("stores")?["Vendors"]:[]),...(allowed("wholesale")?["Wholesalers"]:[]),...(allowed("subscriptions")?["Subscriptions"]:[]),...(allowed("wholesale")?["Marketplace"]:[]),...(role==="owner"?["Admins","Wholesale validity"]:[]),...(allowed("pricing")?["Vendor pricing","Wholesale pricing"]:[]),"Account"];
  useEffect(()=>{if(!tabs.includes(tab))setTab(tabs[0])},[role,permissions.join(","),tab]);
  useEffect(()=>{if(tab==="Vendor pricing")void api("/api/pricing").then(setVendorPricing).catch(error=>setMessage((error as Error).message))},[tab]);
  const list=(tab==="Vendors"?rows.vendors:rows.wholesalers).filter((r:any)=>(r.name+" "+r.owner+" "+r.category+" "+(r.email||"")).toLowerCase().includes(search.toLowerCase()));
  return <main className="global-admin"><header className="global-admin-header"><div><small>SHOPKEEPER PLATFORM</small><h1>Admin dashboard</h1></div><div className="actions"><ThemeToggle/><button className="btn" onClick={()=>void load()} aria-label="Refresh"><RefreshCw size={16}/></button><button className="btn" onClick={()=>void logout()}><LogOut size={16}/> Sign out</button></div></header>
    <nav className="console-tabs" aria-label="Admin sections">{tabs.map(name=><button key={name} className={tab===name?"active":""} onClick={()=>{setTab(name);setSelected(undefined);setSearch("")}}>{name}</button>)}</nav>
    <div className="page"><p role="status" className="status-message">{message}</p>
      {(["Vendors","Wholesalers"].includes(tab)&&!selected)&&<><section className="panel padded"><div className="panel-heading"><div><h2>{tab}</h2><p>Find and manage every {tab==="Vendors"?"retail store":"wholesale seller"} from this list.</p></div></div><label className="search"><Search size={17}/><input aria-label={`Search ${tab}`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search business, owner or category"/></label>
        <div className="admin-business-list">{list.map((r:any)=><button className="admin-business-row" key={r.id} onClick={()=>void open(tab==="Vendors"?"vendor":"wholesale",r.id)}><span><b>{r.name}</b><small>{r.owner} · {r.category}{r.email?" · "+r.email:""}</small></span><span className="badge">{r.suspended||r.disabled?"Disabled":"Active"}</span><span>Open →</span></button>)}{!list.length&&<p className="empty-inline">No matching businesses.</p>}</div></section>
        <section className="panel padded"><h2>Create {tab==="Vendors"?"vendor":"wholesale"} account</h2><p>This account can sign in immediately with the email and initial password you provide.</p><form className="form admin-create-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy(true);try{await api("/api/admin/businesses",{kind:tab==="Vendors"?"vendor":"wholesale",name:f.get("name"),owner:f.get("owner"),email:f.get("email"),phone:f.get("phone"),password:f.get("password"),category:f.get("category")});form.reset();setMessage("Account created. Share the initial password securely; the user can change it in Account settings.");await load()}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}}><label>Business name<input name="name" required/></label><label>Owner name<input name="owner" required/></label><label>Email<input name="email" type="email" required/></label><label>Phone<input name="phone" type="tel"/></label><label>Category<select name="category">{businessTypes.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Initial password<PasswordInput name="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label><button className="btn primary" disabled={busy}>Create account</button></form></section></>}
      {selected&&<section className="panel padded"><button className="btn" onClick={()=>setSelected(undefined)}>← Back to {tab}</button><h2>{selected.name}</h2><p>{selected.owner} · {selected.category} · {selected.phone||"No phone"}</p><div className="metrics"><div className="metric"><span>Subscription</span><strong>{selected.subscription?.daysRemaining??0} days</strong><small>Valid until {stamp(selected.subscription?.validUntil)}</small></div>{selected.kind==="vendor"&&<><div className="metric"><span>Products</span><strong>{selected.products}</strong></div><div className="metric"><span>Sales</span><strong>{selected.sales}</strong><small>{money(selected.revenue)} revenue</small></div></>}</div>
        <h3>Subscription history</h3>{selected.subscription?.history?.map((x:any)=><div className="record-row" key={x.id}><b>{x.plan||x.kind} · {x.status}</b><small>{stamp(x.created_at)} · {x.days} days</small><b>{money(Number(x.amount||0))}</b></div>)}
        {selected.kind==="vendor"&&allowed("subscriptions")&&<form className="form admin-create-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{await api("/api/store",{type:"subscription_extend",vendorId:selected.id,id:crypto.randomUUID(),days:Number(f.get("days")),reference:f.get("reason")});form.reset();setMessage("Vendor subscription extended.");await open("vendor",selected.id);await load()}catch(error){setMessage((error as Error).message)}}}><label>Extend subscription (days)<input name="days" type="number" min="1" max="3650" required/></label><label>Reason<input name="reason" maxLength={100} required/></label><button className="btn primary">Extend validity</button></form>}
        <h3>Team and accounts</h3>{selected.employees?.map((x:any)=><div className="record-row" key={x.id}><b>{x.name}</b><small>{x.email} · {x.employee_designation||"Account owner"}</small></div>)}
        <h3>Orders</h3>{selected.orders?.map((x:any)=><div className="record-row" key={x.id}><b>#{x.id.slice(0,8).toUpperCase()} · {x.other}</b><small>{stamp(x.created_at)}</small><span className="badge">{x.status}</span></div>)}
        <h3>Payments</h3>{selected.payments?.map((x:any)=><div className="record-row" key={x.id}><b>{money(Number(x.amount))} · {x.payment_status}</b><small>Order #{x.request_id.slice(0,8).toUpperCase()} · {stamp(x.created_at)} · {x.reference||"No reference"}</small></div>)}
        <h3>Business details</h3><form className="form admin-create-form" key={selected.id} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api(`/api/admin/businesses/${selected.kind}/${selected.id}`,{name:f.get("name"),owner:f.get("owner"),phone:f.get("phone"),category:f.get("category")});setMessage("Business details saved.");await open(selected.kind,selected.id);await load()}catch(error){setMessage((error as Error).message)}}}><label>Business name<input name="name" defaultValue={selected.name} required/></label><label>Owner name<input name="owner" defaultValue={selected.owner} required/></label><label>Phone<input name="phone" defaultValue={selected.phone||""}/></label><label>Category<select name="category" defaultValue={selected.category}>{businessTypes.map(x=><option key={x} value={x}>{x}</option>)}</select></label><button className="btn primary">Save details</button></form>
        <h3>Manage access</h3>{(selected.kind==="vendor"?allowed("subscriptions"):role==="owner")&&<button className="btn" onClick={async()=>{try{if(selected.kind==="vendor"){const current=await api("/api/store?vendor="+encodeURIComponent(selected.id));await api("/api/store",{type:selected.suspended?"vendor_reactivate":"vendor_suspend",vendorId:selected.id,expectedSuspended:selected.suspended,version:current.version})}else await api("/api/wholesalers/"+selected.id,{action:selected.disabled?"enable":"disable"});setMessage("Access updated.");await open(selected.kind,selected.id);await load()}catch(error){setMessage((error as Error).message)}}}>{selected.suspended||selected.disabled?"Enable account":"Disable account"}</button>}
      </section>}
      {tab==="Subscriptions"&&<SubscriptionApprovals/>}{tab==="Marketplace"&&<MarketplaceAdmin/>}{tab==="Admins"&&role==="owner"&&<AdminManagement/>}{tab==="Wholesale validity"&&role==="owner"&&<WholesaleValidityAdmin/>}{tab==="Vendor pricing"&&vendorPricing&&<PricingEditor config={vendorPricing} busy={busy} save={async action=>{setBusy(true);try{await api("/api/store",action);setVendorPricing(await api("/api/pricing"));setMessage("Vendor pricing updated.");return true}catch(error){setMessage((error as Error).message);return false}finally{setBusy(false)}}}/>} {tab==="Wholesale pricing"&&<WholesalePricingAdmin/>}{tab==="Account"&&<AccountPassword/>}
    </div>
  </main>;
}
