import {useRef,useState} from 'react';
import Papa from 'papaparse';
import type {Product} from '@/lib/store';
export function InventoryImport({busy,save}:{busy:boolean;save:(a:any)=>Promise<unknown>}){
 const [rows,setRows]=useState<Product[]>([]),[error,setError]=useState(''),[open,setOpen]=useState(false),[reading,setReading]=useState(false);const id=useRef(crypto.randomUUID());
 async function read(file?:File){if(!file)return;setError('');setRows([]);setReading(true);try{if(file.size>2000000)throw Error('Use a CSV under 2 MB.');const result=Papa.parse<Record<string,string>>(await file.text(),{header:true,skipEmptyLines:'greedy',transformHeader:h=>h.trim().toLowerCase().replace(/^\uFEFF/,'')});if(result.errors.length)throw Error('Invalid CSV: '+result.errors[0].message);if(!result.data.length||result.data.length>500)throw Error('Include 1–500 rows.');const seen=new Set();const parsed=result.data.map((r,i)=>{const number=(key:string,optional=false)=>{if(!r[key]?.trim()){if(optional)return undefined;throw Error(`Row ${i+2}: ${key} is required (enter 0 if applicable).`)}const n=Number(r[key]);if(!Number.isFinite(n)||n<0)throw Error(`Row ${i+2}: invalid ${key}.`);return n};if(!r.name?.trim())throw Error(`Row ${i+2}: product name is required.`);const barcode=r.barcode?.trim()||'ITEM-'+crypto.randomUUID();if(seen.has(barcode))throw Error(`Row ${i+2}: duplicate barcode.`);seen.add(barcode);const stock=number('stock')!;if(!Number.isInteger(stock))throw Error(`Row ${i+2}: stock must be whole units.`);const mrp=number('mrp',true);const price=number('price',true)??mrp;if(price===undefined)throw Error(`Row ${i+2}: enter a selling price or MRP.`);return {id:'',name:r.name.trim(),barcode,category:r.category?.trim()||'General',unit:r.unit?.trim()||'piece',cost:number('cost')!,price,stock,min:10,target:Math.max(stock,50),mrp,weight:r.weight?.trim().slice(0,50)||'',discountMode:'inherit' as const,specialDiscount:['true','yes','1'].includes((r.special_discount||'').trim().toLowerCase())};});setRows(parsed);id.current=crypto.randomUUID()}catch(e){setError((e as Error).message)}finally{setReading(false)}}
 function template(){const url=URL.createObjectURL(new Blob(['name,barcode,category,unit,weight,cost,price,stock,mrp,special_discount\nNotebook,NOTE-001,Stationery,piece,500 g,30,50,20,50,yes\n'],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='inventory-template.csv';a.click();URL.revokeObjectURL(url)}
 return <section className="panel import-panel"><div className="actions"><button className="btn" onClick={()=>setOpen(!open)}>Import inventory CSV</button><button className="text-button" onClick={template}>Download template</button></div>{open&&<><p>Add new products using CSV (Excel: Save as CSV UTF-8). Blank barcodes receive an internal code; blank selling prices use MRP. Existing barcodes are rejected; no products are overwritten.</p><input type="file" accept=".csv,text/csv" disabled={busy||reading} onChange={e=>{void read(e.target.files?.[0]);e.target.value=''}}/>{error&&<p role="alert" className="notice error">{error}</p>}{!!rows.length&&<><div className="table-scroll"><table className="ledger-table"><thead><tr><th>Name</th><th>Barcode</th><th>Cost</th><th>Price</th><th>Stock</th></tr></thead><tbody>{rows.slice(0,20).map(r=><tr key={r.barcode}><td>{r.name}</td><td>{r.barcode}</td><td>{r.cost}</td><td>{r.price}</td><td>{r.stock}</td></tr>)}</tbody></table></div><p>{rows.length} products ready. Preview shows the first 20.</p><button className="btn primary" disabled={busy||reading} onClick={async()=>{if(await save({type:'inventory_import',id:id.current,items:rows})){setRows([]);setError('Import completed.');id.current=crypto.randomUUID()}}}>Import {rows.length} products</button></>}</>}</section>;
}
