import {createRoot} from 'react-dom/client';
import {useEffect,useState} from 'react';
import {Store} from 'lucide-react';
import {Toaster} from 'sonner';
import App from './App';
import {Pricing} from './pricing';
import {ThemeToggle,initializeTheme} from './theme';
initializeTheme();
import {api} from './api';
import './styles.css';
const adminPortal=location.pathname==='/admin/login';
function Root(){const [ready,setReady]=useState(false),[signed,setSigned]=useState(false),[error,setError]=useState(''),[mode,setMode]=useState(location.hash.startsWith('#activate=')?'activate':location.hash.startsWith('#reset=')?'reset':'login'),[busy,setBusy]=useState(false);const [code,setCode]=useState(decodeURIComponent(location.hash.split('=')[1]??''));useEffect(()=>{history.replaceState(null,'',location.pathname);api('/api/auth/me').then(d=>{if(adminPortal&&d.user.role!=='owner')setError('Sign in with an administrator account.');else setSigned(true)}).catch(()=>{}).finally(()=>setReady(true));const expired=(event:Event)=>{setSigned(false);setError((event as CustomEvent<string>).detail||'Your session ended. Please sign in again.');setMode('login')};window.addEventListener('session-expired',expired);return()=>window.removeEventListener('session-expired',expired)},[]);if(!ready)return <main className="account-gate">Loading Shopkeeper…</main>;if(signed&&mode==='login')return <App/>;
return <main className="account-gate"><Toaster richColors/><section className="panel"><ThemeToggle/><Store size={36}/><h1>{mode==='login'?(adminPortal?'Administrator sign in':'Sign in to Shopkeeper'):mode==='activate'?'Activate your vendor account':'Reset your password'}</h1><p>Use your own account to manage your assigned stores.</p>{error&&<div role="alert" className="notice error">{error}</div>}<form className="form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await api('/api/auth/'+mode,{email:f.get('email'),password:f.get('password'),portal:adminPortal?'admin':'vendor',...(mode!=='login'?{token:code}:{})});if(mode==='reset'){setSigned(false);setMode('login');setError('Password updated. Sign in with your new password.')}else {setMode('login');setSigned(true)}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Email<input name="email" type="email" autoComplete="username" required/></label>{mode!=='login'&&<label>{mode==='activate'?'Activation':'Reset'} code<input value={code} onChange={e=>setCode(e.target.value)} required autoComplete="off"/></label>}<label>Password<input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='login'?1:12} maxLength={128} required/></label>{mode!=='login'&&<small>Use at least 12 characters.</small>}<button className="btn primary" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':mode==='activate'?'Create my account':'Set new password'}</button></form><div className="actions">{(adminPortal?['login','reset']:['login','activate','reset']).filter(x=>x!==mode).map(x=><button className="text-button" key={x} onClick={()=>{setMode(x);setError('')}}>{x==='login'?'Sign in':x==='activate'?'Activate account':'Reset password'}</button>)}</div><a href={adminPortal?'/':'/admin/login'} className="text-button">{adminPortal?'Vendor sign in':'Administrator sign in'}</a><a href="/pricing" className="text-button">View plans · 10-day free trial</a><small className="muted">Activation and reset codes are provided by your store administrator.</small></section></main>}
createRoot(document.getElementById('root')!).render(location.pathname==='/pricing'?<Pricing/>:<Root/>);
