import {createRoot} from 'react-dom/client';
import {useEffect,useState} from 'react';
import {BadgeCheck,ShieldCheck,Store,Truck} from 'lucide-react';
import {Toaster} from 'sonner';
import App from './App';
import {Pricing} from './pricing';
import {ThemeToggle,initializeTheme} from './theme';
initializeTheme();
import {api} from './api';
import {PasswordInput} from './password-input';
import {WholesalePortal} from './wholesale-portal';
import './styles.css';
const superPortal=location.pathname==='/super-admin/login';const wholesalePortal=location.pathname==='/wholesale/login';const adminPortal=superPortal||location.pathname==='/admin/login';
function Root(){const [ready,setReady]=useState(false),[signed,setSigned]=useState(false),[error,setError]=useState(''),[mode,setMode]=useState(location.hash.startsWith('#activate=')?'activate':location.hash.startsWith('#reset=')?'reset':'login'),[busy,setBusy]=useState(false);const [code,setCode]=useState(decodeURIComponent(location.hash.split('=')[1]??''));useEffect(()=>{history.replaceState(null,'',location.pathname+location.search);api('/api/auth/me').then(d=>{if((superPortal&&d.user.role!=='owner')||(adminPortal&&!['owner','admin'].includes(d.user.role))||(wholesalePortal&&d.user.role!=='wholesale'))setError('Sign in with the correct account for this portal.');else setSigned(true)}).catch(()=>{}).finally(()=>setReady(true));const expired=(event:Event)=>{setSigned(false);setError((event as CustomEvent<string>).detail||'Your session ended. Please sign in again.');setMode('login')};window.addEventListener('session-expired',expired);return()=>window.removeEventListener('session-expired',expired)},[]);if(!ready)return <main className="account-gate">Loading Shopkeeper…</main>;if(signed&&mode==='login')return wholesalePortal?<WholesalePortal/>:<App/>;
return <main className="account-gate"><Toaster richColors/><section className="panel"><ThemeToggle/><Store size={36}/><h1>{mode==='login'?(superPortal?'Super admin sign in':wholesalePortal?'Wholesale seller sign in':adminPortal?'Administrator sign in':'Sign in to Shopkeeper'):mode==='activate'?'Activate your vendor account':'Reset your password'}</h1><p>{wholesalePortal?'Publish products, confirm retailer orders and manage delivery.':adminPortal?'Manage subscriptions, access and marketplace quality.':'Bill customers, control stock and order directly from wholesalers.'}</p>{mode==='login'&&!adminPortal&&!wholesalePortal&&<div className="portal-choices"><a className="portal-choice active" href="/"><Store/><span><b>Retail vendor</b><small>POS, inventory and supply orders</small></span></a><a className="portal-choice" href="/wholesale/login"><Truck/><span><b>Wholesaler</b><small>Catalogue, order confirmation and delivery</small></span></a><a className="portal-choice" href="/admin/login"><ShieldCheck/><span><b>Administrator</b><small>Access and subscription control</small></span></a></div>}{error&&<div role="alert" className="notice error">{error}</div>}<form className="form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await api('/api/auth/'+mode,{email:f.get('email'),password:f.get('password'),portal:superPortal?'super-admin':wholesalePortal?'wholesale':adminPortal?'admin':'vendor',...(mode!=='login'?{token:code}:{})});if(mode==='reset'){setSigned(false);setMode('login');setError('Password updated. Sign in with your new password.')}else {setMode('login');setSigned(true)}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Email<input name="email" type="email" autoComplete="username" required/></label>{mode!=='login'&&<label>{mode==='activate'?'Activation':'Reset'} code<input value={code} onChange={e=>setCode(e.target.value)} required autoComplete="off"/></label>}<label>Password<PasswordInput name="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='login'?1:12} maxLength={128} required/></label>{mode!=='login'&&<small>Use at least 12 characters.</small>}<button className="btn primary" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':mode==='activate'?'Create my account':'Set new password'}</button></form><div className="actions">{((adminPortal||wholesalePortal)?['login','reset']:['login','activate','reset']).filter(x=>x!==mode).map(x=><button className="text-button" key={x} onClick={()=>{setMode(x);setError('')}}>{x==='login'?'Sign in':x==='activate'?'Activate account':'Reset password'}</button>)}</div><a href="/pricing" className="trust-link"><BadgeCheck size={16}/>View plans and start free</a><small className="muted">Activation and reset codes are provided by your administrator.</small></section></main>}
createRoot(document.getElementById('root')!).render(location.pathname==='/pricing'?<Pricing/>:<Root/>);
