import {useEffect,useRef,useState} from 'react';
import {api} from './api';
async function prepareImage(file:File,logo=false){
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024)throw Error('Choose JPG, PNG or WebP under 8 MB.');const image=await createImageBitmap(file);
 try{if(image.width*image.height>24000000)throw Error('Choose an image under 24 megapixels.');const scale=Math.min(1,(logo?320:1600)/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const context=canvas.getContext('2d');if(!context)throw Error('Image processing unavailable.');context.drawImage(image,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/webp',.85);if(data.length>2300000)throw Error('Image is too large; please crop it first.');return data;}finally{image.close()}
}
export function StoreLogo({vendorId,logo,onChange}:{vendorId:string;logo:string|null;onChange:(logo:string|null)=>void}){const alive=useRef(true);useEffect(()=>()=>{alive.current=false},[]);const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function upload(file?:File){if(!file)return;setBusy(true);setMessage('');try{const image=await prepareImage(file,true);const r=await api('/api/vendors/'+vendorId+'/logo',{image});if(!alive.current)return;onChange(r.logo);setMessage('Store logo updated.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel padded logo-settings"><h2>Store logo</h2><p className="muted">Display your shop identity in the sidebar and page header.</p>{logo&&<img className="logo-preview" src={logo} alt="Current store logo"/>}<label className="btn">{busy?'Uploading…':'Upload logo'}<input type="file" hidden accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{void upload(e.target.files?.[0]);e.target.value=''}}/></label>{logo&&<button className="text-button" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/api/vendors/'+vendorId+'/logo',{remove:true});if(!alive.current)return;onChange(null);setMessage('Logo removed.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}>Remove logo</button>}<p className="muted small">PNG, JPG or WebP, up to 8 MB. Images are resized before saving.</p><p role="status">{message}</p></section>;
}
export function PaymentProof({vendorId,paymentId,hasProof=false,upload=false,onUploaded}:{vendorId?:string;paymentId:string;hasProof?:boolean;upload?:boolean;onUploaded?:()=>void}){const alive=useRef(true);useEffect(()=>()=>{alive.current=false},[]);const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[localProof,setLocalProof]=useState(false),[show,setShow]=useState(false);const url='/api/vendors/'+encodeURIComponent(vendorId||'')+'/payment-proof/'+encodeURIComponent(paymentId);
 async function save(file?:File){if(!file||!vendorId)return;setBusy(true);setMessage('');try{await api(url,{image:await prepareImage(file)});if(!alive.current)return;setLocalProof(true);setShow(false);setMessage('Screenshot uploaded for administrator review.');onUploaded?.()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 if(!vendorId)return null;
 return <div className="proof-control">{(hasProof||localProof)&&<button type="button" className="text-button" onClick={()=>setShow(!show)}>{show?'Hide':'View'} screenshot</button>}{upload&&<label className="btn">{busy?'Uploading…':'Upload payment screenshot'}<input hidden type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{void save(e.target.files?.[0]);e.target.value=''}}/></label>}{show&&(hasProof||localProof)&&<a href={url} target="_blank" rel="noreferrer"><img src={url} className="proof-preview" alt="Uploaded payment proof; verify against bank records"/></a>}{message&&<p role="status">{message}</p>}</div>;
}
