import {useEffect,useMemo,useState} from 'react';
import {IndianRupee,Package,RotateCcw,ShoppingCart} from 'lucide-react';
import {api} from './api';
import {money} from '@/lib/store';

type Product={id:string;wholesaler_id:string;business_name:string;name:string;sku:string;unit:string;price:number;stock:number};
const tone=(status:string)=>['completed','paid','received'].includes(status)?'green':['cancelled','rejected'].includes(status)?'red':'amber';
export function VendorWholesale({vendorId}:{vendorId:string}){
 const [products,setProducts]=useState<Product[]>([]),[requests,setRequests]=useState<any[]>([]),[returns,setReturns]=useState<any[]>([]),[transactions,setTransactions]=useState<any[]>([]),[qty,setQty]=useState<Record<string,number>>({}),[seller,setSeller]=useState(''),[notes,setNotes]=useState(''),[message,setMessage]=useState(''),[tab,setTab]=useState('Overview');
 async function load(){try{const d=await api('/api/wholesale/catalog?vendor='+encodeURIComponent(vendorId));setProducts(d.products);setRequests(d.requests);setReturns(d.returns);setTransactions(d.transactions);setMessage('')}catch(e){setMessage((e as Error).message)}}
 useEffect(()=>{void load()},[vendorId]);
 const sellers=[...new Map(products.map(p=>[p.wholesaler_id,p.business_name])).entries()],shown=products.filter(p=>!seller||p.wholesaler_id===seller),selected=useMemo(()=>products.filter(p=>qty[p.id]>0),[products,qty]);
 async function send(){if(!selected.length)return;const sellerId=selected[0].wholesaler_id;if(selected.some(p=>p.wholesaler_id!==sellerId)){setMessage('Send a separate request to each wholesale seller.');return}try{await api('/api/wholesale/requests',{vendorId,notes,items:selected.map(p=>({productId:p.id,quantity:qty[p.id]}))});setQty({});setNotes('');setMessage('Quantity request sent to the wholesale seller.');await load();setTab('Requests')}catch(e){setMessage((e as Error).message)}}
 const open=requests.filter(r=>['pending','accepted'].includes(r.status)).length,returnValue=returns.reduce((sum,r)=>sum+Number(r.quantity)*Number(r.unit_price),0),paid=transactions.filter(t=>t.payment_status==='paid').reduce((sum,t)=>sum+Number(t.amount),0);
 return <div className="vendor-wholesale-console"><div className="console-tabs" role="tablist">{['Overview','Catalog','Requests','Returns','Payments'].map(x=><button role="tab" aria-selected={tab===x} className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{message&&<p role="status" className="status-message">{message}</p>}
 {tab==='Overview'&&<><div className="metrics"><div className="metric"><div><span>Available products</span><span className="metric-icon tone-0"><Package size={18}/></span></div><strong>{products.length}</strong><small>From approved wholesale catalogs</small></div><div className="metric"><div><span>Open requests</span><span className="metric-icon tone-1"><ShoppingCart size={18}/></span></div><strong>{open}</strong><small>Pending or accepted orders</small></div><div className="metric"><div><span>Returns value</span><span className="metric-icon tone-2"><RotateCcw size={18}/></span></div><strong>{money(returnValue)}</strong><small>{returns.length} return records</small></div><div className="metric"><div><span>Paid to wholesale</span><span className="metric-icon tone-3"><IndianRupee size={18}/></span></div><strong>{money(paid)}</strong><small>Recorded paid transactions</small></div></div><section className="panel padded"><h2>Wholesale activity</h2>{requests.slice(0,5).map(r=><RequestRow row={r} key={r.id}/>)}{!requests.length&&<p className="empty-inline">No wholesale activity yet. Open Catalog to request products.</p>}</section></>}
 {tab==='Catalog'&&<Catalog products={shown} all={products} sellers={sellers} seller={seller} setSeller={setSeller} qty={qty} setQty={setQty} selected={selected} notes={notes} setNotes={setNotes} send={send}/>} {tab==='Requests'&&<section className="panel padded"><h2>My wholesale requests</h2>{requests.map(r=><RequestRow row={r} key={r.id}/>)}{!requests.length&&<p className="empty-inline">No wholesale requests yet.</p>}</section>} {tab==='Returns'&&<ReturnManager vendorId={vendorId} requests={requests} returns={returns} reload={load} setMessage={setMessage}/>} {tab==='Payments'&&<section className="panel table-scroll"><table className="ledger-table"><thead><tr>{['Wholesale seller','Amount','Status','Reference','Date'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{transactions.map(t=><tr key={t.id}><td>{t.business_name}</td><td>{money(Number(t.amount))}</td><td><span className={'badge '+tone(t.payment_status)}>{t.payment_status}</span></td><td>{t.reference||'—'}</td><td>{new Date(Number(t.created_at)).toLocaleDateString('en-IN')}</td></tr>)}</tbody></table>{!transactions.length&&<p className="empty-inline">No wholesale payments recorded.</p>}</section>}</div>;
}

function Catalog({products,all,sellers,seller,setSeller,qty,setQty,selected,notes,setNotes,send}:{products:Product[];all:Product[];sellers:[string,string][];seller:string;setSeller:(x:string)=>void;qty:Record<string,number>;setQty:(x:Record<string,number>)=>void;selected:Product[];notes:string;setNotes:(x:string)=>void;send:()=>Promise<void>}){return <section className="panel padded"><div className="panel-heading"><div><h2>Approved wholesale catalog</h2><p>Only products shared with your store are visible here.</p></div>{sellers.length>1&&<select aria-label="Wholesale seller" value={seller} onChange={e=>setSeller(e.target.value)}><option value="">All sellers</option>{sellers.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select>}</div><div className="product-grid">{products.map(p=><article className="catalog-card" key={p.id}><b>{p.name}</b><small>{p.business_name} · {p.unit}{p.sku?' · '+p.sku:''}</small><strong>{money(Number(p.price))}</strong><small>{p.stock} available</small><label>Quantity<input type="number" min="0" max={p.stock} value={qty[p.id]||''} onChange={e=>setQty({...qty,[p.id]:Math.max(0,Number(e.target.value))})}/></label></article>)}</div>{!all.length&&<div className="empty-inline"><Package size={24}/><div><b>No wholesale catalog is shared with this store</b><p>Ask the wholesale seller to select your vendor account under Catalog visibility.</p></div></div>}{all.length>0&&!products.length&&<p className="empty-inline">No products match this wholesale seller.</p>}{selected.length>0&&<div className="request-bar"><label>Request note<input value={notes} onChange={e=>setNotes(e.target.value)} maxLength={500}/></label><b>{money(selected.reduce((t,p)=>t+Number(p.price)*(qty[p.id]||0),0))}</b><button className="btn primary" onClick={()=>void send()}>Send quantity request</button></div>}</section>}
function RequestRow({row:r}:{row:any}){return <div className="record-row"><div><b>{r.business_name}</b><small>{r.items.map((i:any)=>i.name+' × '+i.quantity).join(', ')}</small></div><b>{money(Number(r.total))}</b><span className={'badge '+tone(r.status)}>{r.status}</span></div>}
function ReturnManager({vendorId,requests,returns,reload,setMessage}:{vendorId:string;requests:any[];returns:any[];reload:()=>Promise<void>;setMessage:(x:string)=>void}){const lines=requests.filter(r=>r.status==='completed').flatMap(r=>r.items.map((i:any)=>({...i,requestId:r.id,businessName:r.business_name}))),[lineKey,setLineKey]=useState('');const line=lines.find(x=>x.requestId+'|'+x.product_id===lineKey);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(!line)return;try{await api('/api/wholesale/returns',{vendorId,requestId:line.requestId,productId:line.product_id,quantity:Number(f.get('quantity')),unitPrice:Number(f.get('unitPrice')),reason:f.get('reason')});setMessage('Product return submitted for wholesale approval.');setLineKey('');(e.currentTarget as HTMLFormElement).reset();await reload()}catch(error){setMessage((error as Error).message)}}return <div className="wholesale-layout"><section className="panel padded"><h2>Return wholesale product</h2><p>Choose an item from a completed order and enter the return quantity and unit price.</p><form className="form" onSubmit={submit}><label>Completed product<select value={lineKey} onChange={e=>setLineKey(e.target.value)} required><option value="">Select product</option>{lines.map(x=><option key={x.requestId+'|'+x.product_id} value={x.requestId+'|'+x.product_id}>{x.businessName} · {x.name} · {x.quantity} {x.unit}</option>)}</select></label><label>Return quantity<input name="quantity" type="number" min="1" max={line?.quantity||1} step="1" required disabled={!line}/></label><label>Return unit price<input name="unitPrice" type="number" min=".01" max={line?.unit_price||0} step=".01" defaultValue={line?Number(line.unit_price):''} key={lineKey+'-price'} required disabled={!line}/></label><label>Reason<textarea name="reason" maxLength={300} required disabled={!line} placeholder="Damaged, expired, wrong item…"/></label><button className="btn primary" disabled={!line}>Submit product return</button></form></section><section className="panel table-scroll"><table className="ledger-table"><thead><tr>{['Product','Wholesale seller','Quantity','Unit price','Total','Status'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{returns.map(r=><tr key={r.id}><td>{r.product_name}</td><td>{r.business_name}</td><td>{r.quantity} {r.unit}</td><td>{money(Number(r.unit_price))}</td><td>{money(Number(r.quantity)*Number(r.unit_price))}</td><td><span className={'badge '+tone(r.status)}>{r.status}</span></td></tr>)}</tbody></table>{!returns.length&&<p className="empty-inline">No product returns submitted.</p>}</section></div>}
