import {useEffect,useMemo,useState} from 'react';
import {Package,RefreshCw,LogOut,Users,RotateCcw,ShoppingCart,IndianRupee} from 'lucide-react';
import {api,logout} from './api';
import {money} from '@/lib/store';
import {PasswordInput} from './password-input';
import {ThemeToggle} from './theme';

const statusTone=(status:string)=>['completed','paid','processed','received'].includes(status)?'green':['cancelled','rejected'].includes(status)?'red':'amber';
export function WholesalePortal(){
 const [data,setData]=useState<any>(),[tab,setTab]=useState('Overview'),[message,setMessage]=useState(''),[editing,setEditing]=useState<any>();
 async function load(){try{setData(await api('/api/wholesale/portal'));setMessage('')}catch(e){setMessage((e as Error).message)}}
 useEffect(()=>{void load()},[]);
 async function post(path:string,body:any){try{setData(await api(path,body));setMessage('Saved successfully.');setEditing(undefined)}catch(e){setMessage((e as Error).message)}}
 if(!data)return <main className="account-gate">{message||'Loading wholesale portal…'}</main>;
 const tabs=['Overview','Requests','Products','Vendors','Transactions','Returns','Refunds','Account'];
 return <main className="wholesale-portal"><header className="wholesale-header"><div><Package/><b>{data.profile.business_name}</b><small>Wholesale seller console</small></div><nav>{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><ThemeToggle/><button className="btn icon-only" aria-label="Refresh wholesale data" title="Refresh" onClick={()=>void load()}><RefreshCw size={17}/></button><button className="btn" onClick={logout}><LogOut size={16}/>Sign out</button></header><div className="page"><div className="page-heading"><div><span className="eyebrow">WHOLESALE MANAGEMENT</span><h1>{tab}</h1><p>Manage products, selected vendors, quantity requests, returns and payments.</p></div>{tab==='Products'&&<button className="btn primary" onClick={()=>setEditing({active:true})}>Add product</button>}</div>{message&&<p role="status" className="status-message">{message}</p>}
 {tab==='Overview'&&<Overview data={data}/>} {tab==='Requests'&&<Requests data={data} post={post}/>} {tab==='Products'&&<Products data={data} edit={setEditing}/>} {tab==='Vendors'&&<VendorAccess data={data} post={post}/>} {tab==='Transactions'&&<Transactions data={data} post={post}/>} {tab==='Returns'&&<Returns data={data} post={post}/>} {tab==='Refunds'&&<Refunds data={data} post={post}/>} {tab==='Account'&&<section className="panel padded"><h2>Seller account</h2><p>{data.profile.email}</p><p>{data.profile.phone||'No phone'} · {data.profile.address||'No address'}</p><PasswordChange/></section>}
 {editing&&<div className="panel wholesale-editor"><h2>{editing.id?'Edit':'Add'} wholesale product</h2><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post('/api/wholesale/products',{id:editing.id,name:f.get('name'),sku:f.get('sku'),unit:f.get('unit'),price:Number(f.get('price')),stock:Number(f.get('stock')),active:f.get('active')==='on'})}}><label>Product name<input name="name" defaultValue={editing.name} required/></label><label>Barcode / SKU (optional)<input name="sku" defaultValue={editing.sku}/></label><label>Pack / unit<input name="unit" defaultValue={editing.unit||'piece'} required/></label><label>Wholesale price<input name="price" type="number" min=".01" step=".01" defaultValue={editing.price} required/></label><label>Available stock<input name="stock" type="number" min="0" step="1" defaultValue={editing.stock??''} required/></label><label className="check-row"><input name="active" type="checkbox" defaultChecked={editing.active!==false}/> Product is active</label><div className="actions"><button className="btn primary">Save product</button><button type="button" className="btn" onClick={()=>setEditing(undefined)}>Cancel</button></div></form></div>}</div></main>;
}

function Overview({data}:{data:any}){const sales=data.transactions.filter((x:any)=>x.payment_status==='paid').reduce((sum:number,x:any)=>sum+Number(x.amount),0),returns=data.returns.filter((x:any)=>!['received','rejected'].includes(x.status));return <div className="wholesale-dashboard"><div className="metrics"><div className="metric"><div><span>Products</span><span className="metric-icon tone-0"><Package size={18}/></span></div><strong>{data.products.length}</strong><small>{data.products.filter((x:any)=>x.active).length} active products</small></div><div className="metric"><div><span>Selected vendors</span><span className="metric-icon tone-1"><Users size={18}/></span></div><strong>{data.vendors.filter((x:any)=>x.selected).length}</strong><small>Can view your catalog</small></div><div className="metric"><div><span>Open requests</span><span className="metric-icon tone-2"><ShoppingCart size={18}/></span></div><strong>{data.requests.filter((x:any)=>['pending','accepted'].includes(x.status)).length}</strong><small>Need your attention</small></div><div className="metric"><div><span>Paid transactions</span><span className="metric-icon tone-3"><IndianRupee size={18}/></span></div><strong>{money(sales)}</strong><small>{returns.length} open returns</small></div></div><div className="bottom-grid"><section className="panel padded"><h2>Recent vendor requests</h2>{data.requests.slice(0,5).map((r:any)=><div className="record-row" key={r.id}><div><b>{r.vendorName}</b><small>{r.items.map((i:any)=>i.name+' × '+i.quantity).join(', ')}</small></div><b>{money(Number(r.total))}</b><span className={'badge '+statusTone(r.status)}>{r.status}</span></div>)}{!data.requests.length&&<p className="empty-inline">No vendor requests yet.</p>}</section><section className="panel padded"><h2>Return alerts</h2>{data.returns.slice(0,5).map((r:any)=><div className="record-row" key={r.id}><RotateCcw size={18}/><div><b>{r.product_name}</b><small>{r.vendorName} · {r.quantity} {r.unit}</small></div><b>{money(Number(r.quantity)*Number(r.unit_price))}</b></div>)}{!data.returns.length&&<p className="empty-inline">No product returns yet.</p>}</section></div></div>}
function Requests({data,post}:{data:any;post:(p:string,b:any)=>Promise<void>}){return <section className="panel table-scroll"><table className="ledger-table"><thead><tr>{['Vendor','Items','Total','Status','Actions'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.requests.map((r:any)=><tr key={r.id}><td>{r.vendorName}</td><td>{r.items.map((i:any)=>i.name+' × '+i.quantity).join(', ')}</td><td>{money(Number(r.total))}</td><td><span className={'badge '+statusTone(r.status)}>{r.status}</span></td><td className="actions">{r.status==='pending'&&<button className="btn" onClick={()=>void post('/api/wholesale/requests/'+r.id+'/status',{status:'accepted'})}>Accept</button>}{['pending','accepted'].includes(r.status)&&<button className="btn primary" onClick={()=>void post('/api/wholesale/requests/'+r.id+'/status',{status:'completed'})}>Complete</button>}{['pending','accepted'].includes(r.status)&&<button className="text-button" onClick={()=>void post('/api/wholesale/requests/'+r.id+'/status',{status:'cancelled'})}>Cancel</button>}</td></tr>)}</tbody></table>{!data.requests.length&&<p className="empty-inline">Vendor requests will appear here.</p>}</section>}
function Products({data,edit}:{data:any;edit:(x:any)=>void}){return <section className="panel table-scroll"><table className="ledger-table"><thead><tr>{['Product','SKU','Unit','Price','Stock','Status',''].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.products.map((p:any)=><tr key={p.id}><td>{p.name}</td><td>{p.sku||'No barcode / SKU'}</td><td>{p.unit}</td><td>{money(Number(p.price))}</td><td>{p.stock}</td><td><span className={'badge '+(p.active?'green':'amber')}>{p.active?'Active':'Hidden'}</span></td><td><button className="text-button" onClick={()=>edit(p)}>Edit</button></td></tr>)}</tbody></table>{!data.products.length&&<p className="empty-inline">Add products to build your wholesale catalog.</p>}</section>}
function VendorAccess({data,post}:{data:any;post:(p:string,b:any)=>Promise<void>}){const [selected,setSelected]=useState<string[]>([]);useEffect(()=>setSelected(data.vendors.filter((v:any)=>v.selected).map((v:any)=>v.id)),[data.vendors]);return <section className="panel padded vendor-access-panel"><div className="panel-heading"><div><h2>Catalog visibility</h2><p>Only checked vendors can view your product names, prices and stock.</p></div><span className="badge green">{selected.length} selected</span></div><div className="vendor-access-list">{data.vendors.map((v:any)=><label className="vendor-access-row" key={v.id}><input type="checkbox" checked={selected.includes(v.id)} onChange={e=>setSelected(e.target.checked?[...selected,v.id]:selected.filter(id=>id!==v.id))}/><span><b>{v.name}</b><small>{v.id}</small></span><span>{selected.includes(v.id)?'Catalog visible':'Catalog hidden'}</span></label>)}</div>{!data.vendors.length&&<p className="empty-inline">No active vendors are available.</p>}<button className="btn primary" onClick={()=>void post('/api/wholesale/access',{vendorIds:selected})}>Save vendor access</button></section>}
function Transactions({data,post}:{data:any;post:(p:string,b:any)=>Promise<void>}){return <section className="panel padded"><h2>Vendor transactions</h2><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post('/api/wholesale/transactions',{requestId:f.get('requestId'),amount:Number(f.get('amount')),paymentStatus:f.get('paymentStatus'),reference:f.get('reference')})}}><select name="requestId" required>{data.requests.map((r:any)=><option value={r.id} key={r.id}>{r.vendorName} · {r.id.slice(0,8)}</option>)}</select><input name="amount" type="number" min=".01" step=".01" placeholder="Amount" required/><select name="paymentStatus"><option value="paid">Paid</option><option value="partial">Partial</option><option value="pending">Pending</option></select><input name="reference" placeholder="Payment reference"/><button className="btn primary">Record transaction</button></form>{data.transactions.map((t:any)=><div className="record-row" key={t.id}><div><b>{t.vendorName} · {money(Number(t.amount))}</b><small>{t.reference||t.request_id}</small></div><span className={'badge '+statusTone(t.payment_status)}>{t.payment_status}</span></div>)}{!data.transactions.length&&<p className="empty-inline">No transactions recorded.</p>}</section>}
function Returns({data,post}:{data:any;post:(p:string,b:any)=>Promise<void>}){return <section className="panel table-scroll"><table className="ledger-table"><thead><tr>{['Vendor','Product','Quantity','Unit price','Return value','Reason','Status','Action'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.returns.map((r:any)=><tr key={r.id}><td>{r.vendorName}</td><td>{r.product_name}</td><td>{r.quantity} {r.unit}</td><td>{money(Number(r.unit_price))}</td><td>{money(Number(r.quantity)*Number(r.unit_price))}</td><td>{r.reason}</td><td><span className={'badge '+statusTone(r.status)}>{r.status}</span></td><td className="actions">{r.status==='pending'&&<><button className="btn" onClick={()=>void post('/api/wholesale/returns/'+r.id+'/status',{status:'approved'})}>Approve</button><button className="text-button" onClick={()=>void post('/api/wholesale/returns/'+r.id+'/status',{status:'rejected'})}>Reject</button></>}{r.status==='approved'&&<button className="btn primary" onClick={()=>void post('/api/wholesale/returns/'+r.id+'/status',{status:'received'})}>Mark received</button>}</td></tr>)}</tbody></table>{!data.returns.length&&<p className="empty-inline">Vendor product returns will appear here.</p>}</section>}
function Refunds({data,post}:{data:any;post:(p:string,b:any)=>Promise<void>}){return <section className="panel padded"><h2>Payment refund management</h2><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post('/api/wholesale/refunds',{transactionId:f.get('transactionId'),amount:Number(f.get('amount')),reason:f.get('reason'),status:f.get('status')})}}><select name="transactionId" required>{data.transactions.map((t:any)=><option value={t.id} key={t.id}>{t.vendorName} · {money(Number(t.amount))}</option>)}</select><input name="amount" type="number" min=".01" step=".01" placeholder="Refund amount" required/><input name="reason" placeholder="Reason" required/><select name="status"><option value="processed">Processed</option><option value="pending">Pending</option><option value="rejected">Rejected</option></select><button className="btn primary">Record refund</button></form>{data.refunds.map((r:any)=><div className="record-row" key={r.id}><div><b>{money(Number(r.amount))}</b><small>{r.reason}</small></div><span className={'badge '+statusTone(r.status)}>{r.status}</span></div>)}{!data.refunds.length&&<p className="empty-inline">No payment refunds recorded.</p>}</section>}
function PasswordChange(){return <form className="form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await api('/api/auth/password',{currentPassword:f.get('current'),password:f.get('password')});location.reload()}}><label>Current password<PasswordInput name="current" required autoComplete="current-password"/></label><label>New password<PasswordInput name="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label><button className="btn primary">Change password</button></form>}

export function WholesalerManagement(){const [rows,setRows]=useState<any[]>([]),[message,setMessage]=useState(''),[reset,setReset]=useState('');async function load(){try{setRows((await api('/api/wholesalers')).wholesalers)}catch(e){setMessage((e as Error).message)}}useEffect(()=>{void load()},[]);return <section className="panel padded"><h2>Wholesale seller accounts</h2><p role="status">{message}</p>{reset&&<div className="notice break-anywhere">{reset}</div>}<form className="form-grid" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{await api('/api/wholesalers',Object.fromEntries(f));form.reset();setMessage('Wholesale seller created.');await load()}catch(e){setMessage((e as Error).message)}}}><input name="name" placeholder="Contact name" required/><input name="businessName" placeholder="Wholesale business" required/><input name="email" type="email" placeholder="Email" required/><PasswordInput name="password" placeholder="Initial password" minLength={12} maxLength={128} required/><input name="phone" placeholder="Phone"/><input name="address" placeholder="Address"/><button className="btn primary">Add wholesale seller</button></form>{rows.map(r=><div className="record-row" key={r.id}><div><b>{r.business_name}</b><small>{r.name} · {r.email}</small></div><span className={'badge '+(r.disabled?'amber':'green')}>{r.disabled?'Disabled':'Active'}</span><div className="actions"><button className="btn" onClick={async()=>{await api('/api/wholesalers/'+r.id,{action:r.disabled?'enable':'disable'});await load()}}>{r.disabled?'Enable':'Disable'}</button><button className="text-button" onClick={async()=>{const d=await api('/api/wholesalers/'+r.id,{action:'reset'});setReset(location.origin+'/wholesale/login#reset='+encodeURIComponent(d.code))}}>Reset password</button></div></div>)}</section>}
