import test from 'node:test';import assert from 'node:assert/strict';
import {testDatabase} from './pg-helper.mjs';import {migrate} from '../server/db.mjs';import {bootstrap} from '../server/bootstrap.mjs';import {createApp} from '../server/app.mjs';
test('marketplace discovery, quotation, delivery and inventory receiving',async()=>{const db=await testDatabase();await migrate(db);await bootstrap(db,{email:'owner@example.test',password:'Owner-test-password-123',seedDemo:false});const server=createApp(db,{appOrigin:'http://shop.test',frontend:'missing'}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 async function call(path,body,session){const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{Origin:'http://shop.test','Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]}}
 async function login(email,password,portal){const r=await call('/api/auth/login',{email,password,portal});assert.equal(r.status,200);return {cookie:r.cookie,csrf:r.data.csrf}}
 try{const owner=await login('owner@example.test','Owner-test-password-123','super-admin');let r=await call('/api/store',{type:'invite_vendor',vendorId:'main',email:'vendor@example.test'},owner);r=await call('/api/auth/activate',{email:'vendor@example.test',password:'Vendor-password-123',token:r.data.accessCode});const vendor={cookie:r.cookie,csrf:r.data.csrf};assert.equal((await call('/api/wholesalers',{name:'Seller',businessName:'Hosur Foods',email:'seller@example.test',password:'Seller-password-123'},owner)).status,200);const wholesale=await login('seller@example.test','Seller-password-123','wholesale');
  assert.equal((await call('/api/marketplace/profile',{name:'Seller',businessName:'Hosur Foods',gstNumber:'33ABCDE1234F1Z5',phone:'8122187039',address:'Hosur',serviceAreas:'Hosur, Krishnagiri',brands:'RiceCo, FreshMart',minOrder:500,deliveryDays:2,visibilityMode:'public'},wholesale)).status,200);assert.equal((await call('/api/marketplace/products',{name:'Premium rice',sku:'8901234567890',category:'Groceries',description:'25 kg restaurant pack',unit:'25 kg bag',price:900,mrp:1050,stock:50,minQty:2,bulkQty:10,bulkPrice:850,active:true},wholesale)).status,200);
  const admin=(await call('/api/marketplace/admin',undefined,owner)).data,seller=admin.sellers[0];assert.equal((await call('/api/marketplace/admin/verify',{wholesalerId:seller.user_id,verified:true},owner)).status,200);r=await call('/api/marketplace/catalog?vendor=main',undefined,vendor);assert.equal(r.data.products[0].verified,true);const product=r.data.products[0];assert.equal((await call('/api/marketplace/requests',{vendorId:'main',items:[{productId:product.id,quantity:1}]},vendor)).status,400);r=await call('/api/marketplace/requests',{vendorId:'main',items:[{productId:product.id,quantity:2}],notes:'Deliver before noon'},vendor);assert.equal(r.status,200);const order=r.data.requests[0];
  assert.equal((await call('/api/marketplace/requests/'+order.id+'/quote',{deliveryFee:50,deliveryDays:2,notes:'Cash on delivery'},wholesale)).status,200);r=await call('/api/marketplace/requests/'+order.id+'/accept',{vendorId:'main'},vendor);assert.equal(r.data.requests[0].status,'approved');for(const status of ['packed','dispatched','delivered'])assert.equal((await call('/api/marketplace/requests/'+order.id+'/status',{status},wholesale)).status,200);r=await call('/api/marketplace/requests/'+order.id+'/receive',{vendorId:'main'},vendor);assert.equal(r.status,200);assert.equal(r.data.requests[0].inventory_received,true);const store=await call('/api/store?vendor=main',undefined,vendor);assert.equal(store.data.state.products.find(p=>p.name==='Premium rice').stock,2);assert.equal((await call('/api/marketplace/reviews',{vendorId:'main',requestId:order.id,rating:5,comment:'Fast delivery'},vendor)).status,200);assert.equal((await call('/api/marketplace/requests/'+order.id+'/repeat',{vendorId:'main'},vendor)).status,200);assert.ok(Number((await call('/api/marketplace/admin',undefined,owner)).data.summary.orders)>=2);
 }finally{await new Promise(r=>server.close(r));await db.close()}});
