import test from 'node:test';
import assert from 'node:assert/strict';
import {testDatabase} from './pg-helper.mjs';
import {migrate} from '../server/db.mjs';
import {bootstrap} from '../server/bootstrap.mjs';
import {createApp} from '../server/app.mjs';

test('direct wholesale order, delivery payment and vendor margin receiving',async()=>{
 const db=await testDatabase();
 await migrate(db);
 await bootstrap(db,{email:'owner@example.test',password:'Owner-test-password-123',seedDemo:false});
 const server=createApp(db,{appOrigin:'http://shop.test',frontend:'missing'}).listen(0,'127.0.0.1');
 await new Promise(r=>server.once('listening',r));
 const base='http://127.0.0.1:'+server.address().port;
 async function call(path,body,session){
  const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{Origin:'http://shop.test','Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
  return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};
 }
 async function login(email,password,portal){const r=await call('/api/auth/login',{email,password,portal});assert.equal(r.status,200);return {cookie:r.cookie,csrf:r.data.csrf}}
 try{
  const owner=await login('owner@example.test','Owner-test-password-123','super-admin');
  let r=await call('/api/store',{type:'invite_vendor',vendorId:'main',email:'vendor@example.test'},owner);
  r=await call('/api/auth/activate',{email:'vendor@example.test',password:'Vendor-password-123',token:r.data.accessCode});
  const vendor={cookie:r.cookie,csrf:r.data.csrf};
  assert.equal((await call('/api/wholesalers',{name:'Seller',businessName:'Hosur Foods',email:'seller@example.test',password:'Seller-password-123'},owner)).status,200);
  const wholesale=await login('seller@example.test','Seller-password-123','wholesale');
  assert.equal((await call('/api/marketplace/profile',{name:'Seller',businessName:'Hosur Foods',gstNumber:'33ABCDE1234F1Z5',phone:'8122187039',address:'Hosur',serviceAreas:'Hosur, Krishnagiri',brands:'RiceCo, FreshMart',minOrder:500,deliveryDays:2,visibilityMode:'public'},wholesale)).status,200);
  assert.equal((await call('/api/marketplace/payment-settings',{upiId:'hosurfoods@upi',payeeName:'Hosur Foods'},wholesale)).status,200);
  assert.equal((await call('/api/marketplace/products',{name:'Premium rice',sku:'8901234567890',category:'Groceries',description:'25 kg restaurant pack',unit:'25 kg bag',price:900,mrp:1050,stock:50,minQty:2,bulkQty:10,bulkPrice:850,hsnCode:'1006',gstRate:5,active:true},wholesale)).status,200);
  const admin=(await call('/api/marketplace/admin',undefined,owner)).data,seller=admin.sellers[0];
  assert.equal((await call('/api/marketplace/admin/verify',{wholesalerId:seller.user_id,verified:true},owner)).status,200);
  r=await call('/api/marketplace/catalog?vendor=main',undefined,vendor);
  const product=r.data.products[0];
  assert.equal(product.verified,true);
  assert.equal((await call('/api/marketplace/requests',{vendorId:'main',items:[{productId:product.id,quantity:1}]},vendor)).status,400);
  r=await call('/api/marketplace/requests',{vendorId:'main',items:[{productId:product.id,quantity:2}],notes:'Deliver before noon'},vendor);
  assert.equal(r.status,200);
  const order=r.data.requests[0];
  assert.equal(order.items[0].hsn_code,'1006');
  assert.equal(Number(order.items[0].gst_rate),5,'GST metadata is preserved on the invoice line');
  assert.equal(order.status,'pending','new orders wait for wholesaler confirmation');
  assert.equal((await call('/api/marketplace/requests/'+order.id+'/status',{status:'approved'},wholesale)).status,200);
  assert.equal((await call('/api/marketplace/requests/'+order.id+'/status',{status:'packed'},wholesale)).status,200);
  assert.equal((await call('/api/marketplace/requests/'+order.id+'/payment',{paymentStatus:'partial',amount:500,reference:'Cash advance'},wholesale)).status,200);
  assert.equal((await call('/api/marketplace/requests/'+order.id+'/status',{status:'dispatched'},wholesale)).status,200);
  assert.equal((await call('/api/marketplace/requests/'+order.id+'/status',{status:'delivered'},wholesale)).status,200);
  r=await call('/api/marketplace/requests/'+order.id+'/receive',{vendorId:'main',sellingPrices:{[product.id]:1020}},vendor);
  assert.equal(r.status,200);
  assert.equal(r.data.requests[0].inventory_received,true);
  const store=await call('/api/store?vendor=main',undefined,vendor),received=store.data.state.products.find(p=>p.name==='Premium rice');
  assert.equal(received.stock,2);
  assert.equal(received.cost,900);
  assert.equal(received.price,1020,'vendor margin controls the selling price');
  r=await call('/api/marketplace/requests/'+order.id+'/payment-submit',{vendorId:'main',amount:1300,reference:'UPI-426512345678'},vendor);
  assert.equal(r.status,200,'vendor can submit UPI payment after receiving stock');
  const pendingPayment=r.data.transactions.find(x=>x.submitted_by_vendor&&x.payment_status==='pending');
  assert.ok(pendingPayment);
  assert.equal((await call('/api/marketplace/payments/'+pendingPayment.id+'/confirm',{},wholesale)).status,200,'wholesaler confirms vendor payment');
  const payments=(await call('/api/marketplace/catalog?vendor=main',undefined,vendor)).data.transactions;
  assert.equal(payments.filter(x=>['partial','paid'].includes(x.payment_status)).reduce((n,x)=>n+Number(x.amount),0),1800);
  r=await call('/api/wholesale/returns',{vendorId:'main',requestId:order.id,productId:product.id,quantity:1,unitPrice:900,reason:'Damaged bag'},vendor);
  assert.equal(r.status,200,'delivered products can be returned');
  const returnId=r.data.returns[0].id;
  assert.equal((await call('/api/wholesale/returns/'+returnId+'/status',{status:'approved'},wholesale)).status,200);
  assert.equal((await call('/api/wholesale/returns/'+returnId+'/status',{status:'received'},wholesale)).status,200);
  r=await call('/api/marketplace/catalog?vendor=main',undefined,vendor);
  assert.equal(r.data.returns[0].status,'received');
  assert.equal(Number(r.data.returns[0].quantity)*Number(r.data.returns[0].unit_price),900,'received return creates an automatic order credit');
  assert.equal((await call('/api/marketplace/reviews',{vendorId:'main',requestId:order.id,rating:5,comment:'Fast delivery'},vendor)).status,200);
  assert.equal((await call('/api/marketplace/requests/'+order.id+'/repeat',{vendorId:'main'},vendor)).status,200);
  r=await call('/api/employees',{vendorId:'main',name:'Counter Staff',email:'counter@example.test',password:'Counter-password-123',designation:'cashier',permissions:['dashboard','sales']},vendor);
  assert.equal(r.status,200);
  const vendorEmployee=await login('counter@example.test','Counter-password-123');
  assert.equal((await call('/api/store?vendor=main',undefined,vendorEmployee)).status,200,'vendor employee uses the assigned store');
  assert.equal((await call('/api/store',{type:'product',vendorId:'main',version:2,product:{}},vendorEmployee)).status,403,'vendor employee cannot bypass inventory permission');
  r=await call('/api/employees',{name:'Warehouse Staff',email:'warehouse@example.test',password:'Warehouse-password-123',designation:'accountant',permissions:['dashboard','payments']},wholesale);
  assert.equal(r.status,200);
  const wholesaleEmployee=await login('warehouse@example.test','Warehouse-password-123','wholesale');
  const employeePortal=await call('/api/wholesale/portal',undefined,wholesaleEmployee);
  assert.equal(employeePortal.status,200,'wholesale employee uses the parent console');
  assert.deepEqual(employeePortal.data.permissions,['dashboard','payments']);
  assert.equal((await call('/api/marketplace/products',{name:'Blocked'},wholesaleEmployee)).status,403,'wholesale employee cannot bypass inventory permission');
  const employeeRows=(await call('/api/employees',undefined,wholesale)).data.employees;
  assert.equal(employeeRows.length,1);
  assert.equal(employeeRows[0].employee_designation,'accountant');
  assert.equal((await call('/api/employees/'+employeeRows[0].id+'/permissions',{designation:'accountant',permissions:['dashboard','inventory']},wholesale)).status,403,'accountant cannot receive stock access');
  assert.equal((await call('/api/employees/'+employeeRows[0].id+'/permissions',{designation:'order_fulfilment',permissions:['dashboard','inventory']},wholesale)).status,200);
  assert.equal((await call('/api/wholesale/portal',undefined,wholesaleEmployee)).status,401,'changing access revokes existing sessions');
  const relogged=await login('warehouse@example.test','Warehouse-password-123','wholesale');
  assert.deepEqual((await call('/api/wholesale/portal',undefined,relogged)).data.permissions,['dashboard','inventory']);
  assert.equal((await call('/api/store',{type:'vendor_category',vendorId:'main',businessType:'Stationery & books'},owner)).status,200);
  assert.equal((await call('/api/marketplace/catalog?vendor=main',undefined,vendor)).data.products.length,0,'other-category wholesale products disappear');
  const afterCategory=(await call('/api/wholesale/portal',undefined,wholesale)).data;
  assert.ok(!afterCategory.vendors.some(v=>v.id==='main'),'wholesale vendor list follows category');
  assert.ok(afterCategory.requests.some(request=>request.id===order.id),'past orders remain available for payments');
  assert.equal((await call('/api/marketplace/requests',{vendorId:'main',items:[{productId:product.id,quantity:2}]},vendor)).status,403,'catalogue API also enforces category');
  assert.ok(Number((await call('/api/marketplace/admin',undefined,owner)).data.summary.orders)>=2);
 }finally{
  await new Promise(r=>server.close(r));
  await db.close();
 }
});
