import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {testDatabase} from './pg-helper.mjs';import {migrate} from '../server/db.mjs';import {bootstrap} from '../server/bootstrap.mjs';import {createApp} from '../server/app.mjs';
test('limited admins, barcode-free products, subscription queue and wholesale lifecycle',async()=>{const db=await testDatabase();await migrate(db);await bootstrap(db,{email:'owner@example.test',password:'Owner-test-password-123',seedDemo:false});const server=createApp(db,{appOrigin:'http://shop.test',frontend:'missing'}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 async function call(path,body,session){const r=await fetch(base+path,{method:body?'POST':'GET',headers:{Origin:'http://shop.test','Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]}}
 async function login(email,password,portal){const r=await call('/api/auth/login',{email,password,portal});assert.equal(r.status,200);return {cookie:r.cookie,csrf:r.data.csrf}}
 try{const owner=await login('owner@example.test','Owner-test-password-123','super-admin');
  assert.equal((await call('/api/admins',{name:'Billing reviewer',email:'billing@example.test',password:'Billing-password-123',permissions:['subscriptions']},owner)).status,200);const limited=await login('billing@example.test','Billing-password-123','admin');
  let cfg=(await call('/api/pricing')).data;cfg={...cfg,upiId:'merchant@test'};assert.equal((await call('/api/store',{type:'pricing_update',vendorId:'main',version:cfg.version,pricing:cfg},limited)).status,403);assert.equal((await call('/api/subscriptions/pending',undefined,limited)).status,200);const limitedStore=await call('/api/store',undefined,limited);assert.equal(limitedStore.data.state.products.length,0);assert.equal(limitedStore.data.access,undefined);
  let r=await call('/api/store',{type:'invite_vendor',vendorId:'main',email:'vendor@example.test'},owner);r=await call('/api/auth/activate',{email:'vendor@example.test',password:'Vendor-password-123',token:r.data.accessCode});const vendor={cookie:r.cookie,csrf:r.data.csrf};
  r=await call('/api/store',{type:'product',vendorId:'main',version:0,product:{id:'',name:'Loose rice',barcode:'',category:'Staples',unit:'kg',price:60,cost:50,stock:20,min:2,target:30}},vendor);assert.equal(r.status,200);assert.equal(r.data.state.products[0].barcode,'');
  cfg=(await call('/api/pricing')).data;await call('/api/store',{type:'pricing_update',vendorId:'main',version:cfg.version,pricing:{...cfg,upiId:'merchant@test'}},owner);const payment=randomUUID();await call('/api/store',{type:'subscription_order',vendorId:'main',id:payment,plan:'monthly'},vendor);await call('/api/store',{type:'subscription_reference',vendorId:'main',id:payment,reference:'UPI-TEST-123'},vendor);assert.equal((await call('/api/subscriptions/pending',undefined,limited)).data.requests[0].vendorName,'My General Store');assert.equal((await call('/api/subscriptions/'+payment+'/approve',{},limited)).status,200);
  assert.equal((await call('/api/wholesalers',{name:'Whole Seller',businessName:'Hosur Wholesale',email:'whole@example.test',password:'Wholesale-password-123',phone:'9000000000',address:'Hosur'},owner)).status,200);const wholesale=await login('whole@example.test','Wholesale-password-123','wholesale');assert.equal((await call('/api/store',undefined,wholesale)).status,200);
  r=await call('/api/wholesale/products',{name:'Rice bag',sku:'RICE25',unit:'25 kg bag',price:1000,stock:20,active:true},wholesale);assert.equal(r.status,200);const product=r.data.products[0];
  assert.equal((await call('/api/wholesale/catalog?vendor=main',undefined,vendor)).data.products.length,0);r=await call('/api/wholesale/access',{vendorIds:['main']},wholesale);assert.equal(r.data.vendors.find(v=>v.id==='main').selected,true);assert.equal((await call('/api/wholesale/catalog?vendor=main',undefined,vendor)).data.products.length,1);
  r=await call('/api/wholesale/requests',{vendorId:'main',items:[{productId:product.id,quantity:3}],notes:'Deliver Friday'},vendor);assert.equal(r.status,200);const request=r.data.requests[0];r=await call('/api/wholesale/requests/'+request.id+'/status',{status:'accepted'},wholesale);assert.equal(r.data.requests[0].status,'accepted');r=await call('/api/wholesale/requests/'+request.id+'/status',{status:'completed'},wholesale);assert.equal(r.data.products.find(p=>p.id===product.id).stock,17);
  r=await call('/api/wholesale/transactions',{requestId:request.id,amount:3000,paymentStatus:'paid',reference:'CASH-1'},wholesale);const transaction=r.data.transactions[0];r=await call('/api/wholesale/refunds',{transactionId:transaction.id,amount:100,reason:'Damaged bag',status:'processed'},wholesale);assert.equal(r.data.refunds[0].reason,'Damaged bag');
  r=await call('/api/wholesale/returns',{vendorId:'main',requestId:request.id,productId:product.id,quantity:1,unitPrice:900,reason:'Damaged bag'},vendor);assert.equal(r.status,200);assert.equal(r.data.returns[0].quantity,1);const productReturn=r.data.returns[0];r=await call('/api/wholesale/returns/'+productReturn.id+'/status',{status:'approved'},wholesale);assert.equal(r.data.returns[0].status,'approved');r=await call('/api/wholesale/returns/'+productReturn.id+'/status',{status:'received'},wholesale);assert.equal(r.data.products.find(p=>p.id===product.id).stock,18);
  await call('/api/wholesale/access',{vendorIds:[]},wholesale);r=await call('/api/wholesale/catalog?vendor=main',undefined,vendor);assert.equal(r.data.products.length,0);assert.equal(r.data.returns.length,1);
 }finally{await new Promise(r=>server.close(r));await db.close()}});
