import {randomUUID} from 'node:crypto';
import {email,hashPassword,limit,requireSuperAdmin,requireVendor,token,digest} from './security.mjs';
import {transaction} from './db.mjs';
const bad=(message,status=400)=>Object.assign(Error(message),{status});
const text=(value,max=200)=>typeof value==='string'&&value.trim()&&value.length<=max?value.trim():null;
const money=value=>typeof value==='number'&&Number.isFinite(value)&&value>0&&value<=10000000&&Math.round(value*100)===value*100;
function seller(user){if(user.role!=='wholesale')throw bad('Wholesale seller access required.',403)}
async function sellerData(db,id){
 const profile=await db.prepare('SELECT w.*,u.email,u.name,u.disabled FROM wholesalers w JOIN users u ON u.id=w.user_id WHERE w.user_id=?').get(id);
 if(!profile)throw bad('Wholesale seller profile not found.',404);
 const products=await db.prepare('SELECT * FROM wholesale_products WHERE wholesaler_id=? ORDER BY updated_at DESC').all(id);
 const requests=await db.prepare(`SELECT r.*,v.data AS vendor_data,COALESCE(SUM(i.quantity*i.unit_price),0) AS total FROM wholesale_requests r JOIN vendors v ON v.id=r.vendor_id LEFT JOIN wholesale_request_items i ON i.request_id=r.id WHERE r.wholesaler_id=? GROUP BY r.id,v.data ORDER BY r.created_at DESC`).all(id);
 const items=await db.prepare('SELECT i.*,p.name,p.unit FROM wholesale_request_items i JOIN wholesale_products p ON p.id=i.product_id JOIN wholesale_requests r ON r.id=i.request_id WHERE r.wholesaler_id=? ORDER BY p.name').all(id);
 const transactions=await db.prepare('SELECT t.* FROM wholesale_transactions t JOIN wholesale_requests r ON r.id=t.request_id WHERE r.wholesaler_id=? ORDER BY t.created_at DESC').all(id);
 const refunds=await db.prepare('SELECT f.* FROM wholesale_refunds f JOIN wholesale_transactions t ON t.id=f.transaction_id JOIN wholesale_requests r ON r.id=t.request_id WHERE r.wholesaler_id=? ORDER BY f.created_at DESC').all(id);
 return {profile,products,requests:requests.map(r=>({...r,vendorName:JSON.parse(r.vendor_data).settings.name,items:items.filter(i=>i.request_id===r.id)})),transactions,refunds};
}
export function registerWholesaleRoutes(app,db){
 app.get('/api/wholesalers',async(req,res)=>{requireSuperAdmin(req.user);res.json({wholesalers:await db.prepare("SELECT u.id,u.email,u.name,u.disabled,w.business_name,w.phone,w.address,w.created_at FROM users u JOIN wholesalers w ON w.user_id=u.id WHERE u.role='wholesale' ORDER BY w.created_at DESC").all()})});
 app.post('/api/wholesalers',async(req,res)=>{requireSuperAdmin(req.user);await limit(db,'wholesale-create:'+req.user.id,20);const mail=email(req.body.email),name=text(req.body.name,100),business=text(req.body.businessName,150);if(!name||!business)throw bad('Enter the seller and wholesale business names.');const hash=await hashPassword(req.body.password),id=randomUUID();await transaction(db,async()=>{if(await db.prepare('SELECT 1 FROM users WHERE email=?').get(mail))throw bad('An account already uses this email.',409);await db.prepare('INSERT INTO users(id,email,password_hash,role,name,created_at) VALUES(?,?,?,?,?,?)').run(id,mail,hash,'wholesale',name,Date.now());await db.prepare('INSERT INTO wholesalers(user_id,business_name,phone,address,created_at) VALUES(?,?,?,?,?)').run(id,business,text(req.body.phone,30)||'',text(req.body.address,300)||'',Date.now());});res.json({ok:true});});
 app.post('/api/wholesalers/:id',async(req,res)=>{requireSuperAdmin(req.user);let code;await transaction(db,async()=>{const target=await db.prepare("SELECT * FROM users WHERE id=? AND role='wholesale' FOR UPDATE").get(req.params.id);if(!target)throw bad('Wholesale seller not found.',404);if(['enable','disable'].includes(req.body.action)){await db.prepare('UPDATE users SET disabled=? WHERE id=?').run(req.body.action==='disable',target.id);await db.prepare('DELETE FROM sessions WHERE user_id=?').run(target.id);}else if(req.body.action==='reset'){code=token();await db.prepare("DELETE FROM tokens WHERE email=? AND kind='reset'").run(target.email);await db.prepare('INSERT INTO tokens VALUES(?,?,?,?,?)').run(digest(code),target.email,null,'reset',Date.now()+3600000);}else throw bad('Choose enable, disable or reset.');});res.json({ok:true,...(code?{code}:{})});});
 app.get('/api/wholesale/portal',async(req,res)=>{seller(req.user);res.json(await sellerData(db,req.user.id))});
 app.post('/api/wholesale/products',async(req,res)=>{seller(req.user);const p=req.body,id=p.id||randomUUID(),name=text(p.name),unit=text(p.unit,50),sku=typeof p.sku==='string'?p.sku.trim().slice(0,100):'';if(!name||!unit||!money(Number(p.price))||!Number.isInteger(Number(p.stock))||Number(p.stock)<0||Number(p.stock)>10000000)throw bad('Enter a valid product, unit, price and stock.');await db.prepare(`INSERT INTO wholesale_products(id,wholesaler_id,name,sku,unit,price,stock,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,sku=EXCLUDED.sku,unit=EXCLUDED.unit,price=EXCLUDED.price,stock=EXCLUDED.stock,active=EXCLUDED.active,updated_at=EXCLUDED.updated_at WHERE wholesale_products.wholesaler_id=EXCLUDED.wholesaler_id`).run(id,req.user.id,name,sku,unit,Number(p.price),Number(p.stock),p.active!==false,Date.now(),Date.now());res.json(await sellerData(db,req.user.id));});
 app.get('/api/wholesale/catalog',async(req,res)=>{const vendor=await requireVendor(db,req.user,String(req.query.vendor||''));const products=await db.prepare(`SELECT p.*,w.business_name FROM wholesale_products p JOIN wholesalers w ON w.user_id=p.wholesaler_id JOIN users u ON u.id=p.wholesaler_id WHERE p.active=TRUE AND p.stock>0 AND u.disabled=FALSE ORDER BY w.business_name,p.name`).all();const requests=await vendorRequests(db,vendor.id);res.json({products,requests});});
 app.post('/api/wholesale/requests',async(req,res)=>{const vendor=await requireVendor(db,req.user,req.body.vendorId);if(!Array.isArray(req.body.items)||!req.body.items.length||req.body.items.length>100)throw bad('Choose at least one wholesale product.');const ids=req.body.items.map(x=>x.productId);const products=await db.prepare('SELECT * FROM wholesale_products WHERE id=ANY(?) AND active=TRUE FOR UPDATE').all(ids);if(products.length!==new Set(ids).size)throw bad('One or more wholesale products are unavailable.');const wholesaler=products[0].wholesaler_id;if(products.some(p=>p.wholesaler_id!==wholesaler))throw bad('Create a separate request for each wholesale seller.');const id=randomUUID();await transaction(db,async()=>{await db.prepare('INSERT INTO wholesale_requests(id,wholesaler_id,vendor_id,status,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(id,wholesaler,vendor.id,'pending',text(req.body.notes,500)||'',Date.now(),Date.now());for(const item of req.body.items){const p=products.find(x=>x.id===item.productId);if(!Number.isInteger(item.quantity)||item.quantity<1||item.quantity>p.stock)throw bad('Requested quantity exceeds available wholesale stock.');await db.prepare('INSERT INTO wholesale_request_items(request_id,product_id,quantity,unit_price) VALUES(?,?,?,?)').run(id,p.id,item.quantity,p.price);}});res.json({ok:true,requests:await vendorRequests(db,vendor.id)});});
 app.post('/api/wholesale/requests/:id/status',async(req,res)=>{seller(req.user);if(!['accepted','completed','cancelled'].includes(req.body.status))throw bad('Choose a valid request status.');await transaction(db,async()=>{const row=await db.prepare('SELECT * FROM wholesale_requests WHERE id=? AND wholesaler_id=? FOR UPDATE').get(req.params.id,req.user.id);if(!row)throw bad('Request not found.',404);if(row.status==='completed'||row.status==='cancelled')throw bad('This request is already closed.');if(req.body.status==='completed'){const items=await db.prepare('SELECT * FROM wholesale_request_items WHERE request_id=?').all(row.id);for(const item of items){const changed=await db.prepare('UPDATE wholesale_products SET stock=stock-?,updated_at=? WHERE id=? AND wholesaler_id=? AND stock>=?').run(item.quantity,Date.now(),item.product_id,req.user.id,item.quantity);if(!changed.changes)throw bad('Insufficient wholesale stock to complete this request.');}}await db.prepare('UPDATE wholesale_requests SET status=?,updated_at=? WHERE id=?').run(req.body.status,Date.now(),row.id);});res.json(await sellerData(db,req.user.id));});
 app.post('/api/wholesale/transactions',async(req,res)=>{seller(req.user);if(!money(Number(req.body.amount))||!['pending','paid','partial'].includes(req.body.paymentStatus))throw bad('Enter a valid transaction amount and status.');const request=await db.prepare('SELECT id FROM wholesale_requests WHERE id=? AND wholesaler_id=?').get(req.body.requestId,req.user.id);if(!request)throw bad('Request not found.',404);await db.prepare('INSERT INTO wholesale_transactions(id,request_id,amount,payment_status,reference,created_at) VALUES(?,?,?,?,?,?)').run(randomUUID(),request.id,Number(req.body.amount),req.body.paymentStatus,text(req.body.reference,200)||'',Date.now());res.json(await sellerData(db,req.user.id));});
 app.post('/api/wholesale/refunds',async(req,res)=>{seller(req.user);if(!money(Number(req.body.amount))||!text(req.body.reason,300)||!['pending','processed','rejected'].includes(req.body.status))throw bad('Enter valid refund details.');const t=await db.prepare('SELECT t.* FROM wholesale_transactions t JOIN wholesale_requests r ON r.id=t.request_id WHERE t.id=? AND r.wholesaler_id=?').get(req.body.transactionId,req.user.id);if(!t||Number(req.body.amount)>Number(t.amount))throw bad('Refund exceeds the transaction amount.');await db.prepare('INSERT INTO wholesale_refunds(id,transaction_id,amount,reason,status,created_at) VALUES(?,?,?,?,?,?)').run(randomUUID(),t.id,Number(req.body.amount),req.body.reason.trim(),req.body.status,Date.now());res.json(await sellerData(db,req.user.id));});
}
async function vendorRequests(db,vendorId){const requests=await db.prepare(`SELECT r.*,w.business_name,COALESCE(SUM(i.quantity*i.unit_price),0) AS total FROM wholesale_requests r JOIN wholesalers w ON w.user_id=r.wholesaler_id LEFT JOIN wholesale_request_items i ON i.request_id=r.id WHERE r.vendor_id=? GROUP BY r.id,w.business_name ORDER BY r.created_at DESC`).all(vendorId);const items=await db.prepare('SELECT i.*,p.name,p.unit FROM wholesale_request_items i JOIN wholesale_products p ON p.id=i.product_id JOIN wholesale_requests r ON r.id=i.request_id WHERE r.vendor_id=?').all(vendorId);return requests.map(r=>({...r,items:items.filter(i=>i.request_id===r.id)}));}
