import {initial,demoProducts,mutate,isLow} from './store';
import type {State,Product} from './store';
export const businessTypes=['General store','Grocery & supermarket','Stationery & books','Hardware & electrical','Fashion & accessories','Electronics','Other'];
export type Vendor={id:string;owner:string;type:string;state:State};
export type VendorBook={format:2;vendors:Vendor[];ownerUserId?:string;members?:{userId:string;vendorId:string;email:string}[];invites?:{hash:string;email:string;vendorId:string;expires:number}[]};
export type VendorSummary={id:string;name:string;owner:string;type:string;demo:boolean;products:number;sales:number;revenue:number;low:number;phone:string};
const catalogs=[
[['Classmate Notebook','Notebooks',65,45,'180 pages'],['Apsara Pencils','Writing',60,40,'10 pack'],['Cello Ball Pens','Writing',100,70,'10 pack'],['Fevicol Glue','Art supplies',45,30,'100 g'],['A4 Copier Paper','Paper',280,220,'500 sheets'],['Geometry Box','School supplies',150,105,'piece'],['Watercolour Set','Art supplies',180,125,'12 colours'],['Document Folder','Office supplies',40,25,'piece']],
[['LED Bulb 9W','Electrical',120,85,'piece'],['PVC Insulation Tape','Electrical',25,14,'roll'],['Claw Hammer','Hand tools',350,245,'piece'],['Screwdriver Set','Hand tools',220,150,'6 pieces'],['Wall Plugs','Fasteners',50,30,'50 pack'],['Extension Board','Electrical',480,340,'4 sockets'],['Measuring Tape','Hand tools',130,85,'5 metres'],['Brass Padlock','Locks',290,200,'50 mm']]
] as const;
function demoVendor(id:string,name:string,type:string,index:number,now=new Date()):Vendor{const state=initial();state.demo=true;state.settings={name,phone:'',address:'Demo address · Hosur, Tamil Nadu'};state.products=index===0?demoProducts():catalogs[index-1].map((p,i)=>({id:id+'-p'+i,name:p[0],category:p[1],price:p[2],cost:p[3],unit:p[4],barcode:'DEMO-'+index+'-'+String(i+1).padStart(3,'0'),stock:0,min:10}));state.customers=['Ananya (sample)','Ravi (sample)','Meena (sample)','Kumar (sample)'].map((name,i)=>({id:id+'-c'+i,name,phone:''}));state.suppliers=['Local Wholesale (sample)','City Distributors (sample)'].map((name,i)=>({id:id+'-s'+i,name,phone:''}));
const stamp=(days:number,hour=10)=>{const d=new Date(now);d.setUTCDate(d.getUTCDate()-days);d.setUTCHours(hour,0,0,0);return d.toISOString()};
state.products.forEach((p,i)=>{p.stock=0;mutate(state,{type:'purchase',id:id+'-opening-'+i,product:p.id,qty:75+i*4,cost:p.cost,supplier:state.suppliers[i%2].name});state.purchases[0].date=stamp(29)});
for(let day=27;day>=0;day--){for(let bill=0;bill<2+(day%3);bill++){const p=state.products[(day+bill)%state.products.length];const qty=1+((day+bill)%2);mutate(state,{type:'sale',id:id+'-'+day.toString().padStart(2,'0')+'-'+bill,items:[{id:p.id,qty}],discount:bill===1?Math.min(5,p.price):0,payment:['Cash','UPI','Card'][(day+bill)%3],customer:state.customers[(day+bill)%4].name});state.sales[0].date=day===0?new Date(now.getTime()-bill*60000).toISOString():stamp(day,8+bill);}}
// Small opening quantities on selected items create useful low-stock examples while keeping the stock ledger consistent.
state.products.slice(0,3).forEach((p,i)=>{const target=i===2?0:3+i;const used=state.sales.reduce((n,s)=>n+s.items.filter(x=>x.id===p.id).reduce((a,x)=>a+x.qty,0),0);p.stock=target;const purchase=state.purchases.find(x=>x.id===id+'-opening-'+i)!;purchase.qty=used+target;purchase.total=purchase.qty*p.cost;});
state.expenses=[{id:id+'-rent',date:stamp(20),name:'Shop rent (sample)',amount:1800+index*300},{id:id+'-electricity',date:stamp(8),name:'Electricity (sample)',amount:420+index*50},{id:id+'-packing',date:stamp(2),name:'Packing materials (sample)',amount:150}];return {id,owner:['Lakshmi (sample)','Arun (sample)','Priya (sample)'][index],type,state};}
export function upgradeBook(raw:State|VendorBook,now=new Date()):VendorBook{if('format' in raw&&raw.format===2)return raw;return {format:2,vendors:[{id:'main',owner:'Store owner',type:'General store',state:raw as State},demoVendor('demo-grocery','Lakshmi Fresh Mart','Grocery & supermarket',0,now),demoVendor('demo-stationery','Paper & Pen Store','Stationery & books',1,now),demoVendor('demo-hardware','BuildRight Hardware','Hardware & electrical',2,now)]}}
export function summaries(book:VendorBook):VendorSummary[]{return book.vendors.map(v=>({id:v.id,name:v.state.settings.name,owner:v.owner,type:v.type,demo:v.state.demo,products:v.state.products.length,sales:v.state.sales.length,revenue:v.state.sales.reduce((n,s)=>n+s.total,0),low:v.state.products.filter(p=>isLow(p,v.state)).length,phone:v.state.settings.phone}))}
export function applyVendor(book:VendorBook,selected:string,a:any):string{if(a.type==='vendor_create'){if(typeof a.id!=='string'||!/^vendor-[a-f0-9-]{36}$/.test(a.id))throw Error('Invalid vendor identifier.');if(book.vendors.some(v=>v.id===a.id))return a.id;for(const key of ['name','owner'])if(typeof a[key]!=='string'||!a[key].trim()||a[key].length>150)throw Error('Enter a store name and owner name.');if(!businessTypes.includes(a.businessType)||typeof a.phone!=='string'||a.phone.length>30)throw Error('Enter valid vendor details.');const state=initial();state.settings={name:a.name.trim(),phone:a.phone,address:''};book.vendors.push({id:a.id,owner:a.owner.trim(),type:a.businessType,state});return a.id;}const vendor=book.vendors.find(v=>v.id===selected);if(!vendor)throw Error('Store not found. Choose an available vendor.');if(a.type==='demo')throw Error('Use the separate demo stores in the vendor switcher.');mutate(vendor.state,a);return selected;}
